### ISSUE TITLE
Error when I try to compile a small example 

### ISSUE THREAD

**Issue by e-Evolution** [getquill/protoquill#4]
**Version**: (Last version from master branch)
**Module**: (e.g. `quill-jdbc-zio`)
**Database**: (e.g. `postgresql`)

### Code with example 

```
import io.getquill.context.ZioJdbc.QDataSource
import io.getquill.util.LoadConfig
import io.getquill.{Literal, PostgresZioJdbcContext, context}
import zio.Runtime
import zio.blocking.Blocking
import zio.console.putStrLn
import zio.stream.ZStream

import java.time.{Instant, LocalDateTime}
import scala.util.Try

object Main extends App {
  object context extends PostgresZioJdbcContext(Literal)
  import context._
  case class Person(name: String, age: Int)
  val zioConn =
    QDataSource.fromPrefix("testPostgresDB") >>>
      QDataSource.toConnection

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    val people = quote {
      query[Person].filter(p => p.name == "Alex")
    }
    context
      .run(people)
      .tap(result => putStrLn(result.toString))
      .provideCustomLayer(zioConn)
      .exitCode
  }
}
```

### Expected behavior
The compiler should not show error

### Actual behavior
The compiler error show :
```
getquilltest/target/scala-3.0.0/classes ...
[error] -- Error: /Users/e-Evolution/Develop/Scala/getquilltest/src/main/scala/Main.scala:21:23 
[error] 21 |    val people = quote {
[error]    |                 ^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.NoSuchMethodError: 'scala.util.Try io.getquill.util.LoadObject$.apply(scala.quoted.Type, scala.quoted.Quotes)'
[error]    |	at io.getquill.metaprog.SummonParser$.apply(SummonParser.scala:18)
[error]    |	at io.getquill.context.QuoteMacro$.apply(QuoteMacro.scala:66)
[error]    |
[error]    | This location contains code that was inlined from Main.scala:21
[error]    | This location contains code that was inlined from GetQuill.scala:3
[error] 22 |      query[Person].filter(p => p.name == "Alex")
[error] 23 |    }
[error] -- Error: /Users/e-Evolution/Develop/Scala/getquilltest/src/main/scala/Main.scala:25:10 
[error] 24 |    context
[error] 25 |      .run(people)
[error]    |    ^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.NoSuchMethodError: 'scala.util.Try io.getquill.util.LoadObject$.apply(scala.quoted.Type, scala.quoted.Quotes)'
[error]    |	at io.getquill.context.StaticTranslationMacro$.idiomAndNamingStatic(StaticTranslationMacro.scala:131)
[error]    |	at io.getquill.context.StaticTranslationMacro$.applyInner(StaticTranslationMacro.scala:143)
[error]    |	at io.getquill.context.QueryExecution$RunQuery.applyQuery(QueryExecution.scala:168)
[error]    |	at io.getquill.context.QueryExecution$RunQuery.apply(QueryExecution.scala:147)
[error]    |	at io.getquill.context.QueryExecution$.applyImpl(QueryExecution.scala:297)
[error]    |
[error]    | This location contains code that was inlined from Main.scala:25
[error]    | This location contains code that was inlined from Context.scala:179
[error] two errors found
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed 3 jun. 2021 15:58:17
[IJ]
```

### Steps to reproduce the behavior

1.- git clone https://github.com/getquill/protoquill.git
2.- sbt test:compile
3.- sbt package
4.- sbt publishLocal
5.- create new project source code using build.sh :

```
ThisBuild / scalaVersion := "3.0.0"
ThisBuild / version := "0.1.0-SNAPSHOT"
ThisBuild / organization := "com.example"
ThisBuild / organizationName := "example"

val pgJdbcVersion = "42.2.18"
lazy val root = (project in file("."))
  .settings(
    name := "getquilltest",
    scalaVersion := "3.0.0",
    scalacOptions ++= Seq(
      "-language:implicitConversions"
    ),
    resolvers ++= Seq(
      Resolver.mavenLocal,
      "Local Maven" at Path.userHome.asFile.toURI.toURL + ".ivy2/",
      "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots",
      "Sonatype OSS Releases" at "https://oss.sonatype.org/content/repositories/releases"
    ),
    libraryDependencies ++= Seq(
      "dev.zio" %% "zio" % "1.0.9",
      "dev.zio" %% "zio-streams" % "1.0.8",
      "dev.zio" %% "zio-test" % "1.0.9" % Test,
      ("io.getquill" %% "quill-core-portable" % "3.7.1")
        .cross(CrossVersion.for3Use2_13),
      ("io.getquill" %% "quill-sql-portable" % "3.7.1")
        .cross(CrossVersion.for3Use2_13),
      "quill-sql" %% "quill-sql" % "0.1.0-SNAPSHOT",
      "quill-jdbc" %% "quill-jdbc" % "0.1.0-SNAPSHOT",
      "quill-jdbc-zio" %% "quill-jdbc-zio" % "0.1.0-SNAPSHOT",
      "quill" %% "quill" % "0.1.0-SNAPSHOT",
      "org.postgresql" % "postgresql" % pgJdbcVersion
    ),
    testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework")
  )
```
Source code : 
```
import io.getquill.context.ZioJdbc.{QDataSource, _}
import io.getquill.util.{LoadConfig, _}
import io.getquill.{Literal, PostgresZioJdbcContext, context, _}
import zio.{ExitCode, Runtime, URIO}
import zio.blocking.Blocking
import zio.console.putStrLn
import zio.stream.ZStream

import java.time.{Instant, LocalDateTime}
import scala.util.Try

object Main extends App {
  object context extends PostgresZioJdbcContext(Literal)
  import context._
  case class Person(name: String, age: Int)
  val zioConn =
    QDataSource.fromPrefix("testPostgresDB") >>>
      QDataSource.toConnection

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    val people = quote {
      query[Person].filter(p => p.name == "Alex")
    }
    context
      .run(people)
      .tap(result => putStrLn(result.toString))
      .provideCustomLayer(zioConn)
      .exitCode
  }
}
```

**Comment by deusaquilus** [comment]
@e-Evolution I saw this issue with the IntelliJ build, it was due to a name-conflict. Can you try it again with ProtoQuill Beta 1.4 ?

**Comment by e-Evolution** [comment]
Hi, @deusaquilus Alexander thank you a lot, the problem was solved in the last version.
